[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true  # leave quote style alone, Ruff will handle

[tool.ruff]
line-length = 120
target-version = "py310"

# Enable rulesets (E=pycodestyle, F=pyflakes, W=warnings, C=convention, Q=quotes)
select = ["E", "F", "W", "C", "Q"]
ignore = ["E203", "W503"]  # handled by Black

# Allow auto-fixes
fix = true
unsafe-fixes = true

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
strict_optional = true
