[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true  # keep quotes untouched, Ruff handles style

[tool.ruff]
line-length = 120
target-version = "py310"

# Enable rulesets (E=pycodestyle, F=pyflakes, W=warnings, C=convention, Q=quotes)
select = ["E", "F", "W", "C", "Q"]

# Only ignore W503 (Black prefers line break after binary operator).
# Let Ruff handle E203 auto-fix instead of ignoring it.
ignore = ["W503"]

# Enable auto-fixes
fix = true
unsafe-fixes = true

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
strict_optional = true
